export const VALIDATION_MESSAGE: Record<string, string> = {
  required: '{attribute} field is required',
  email: 'Email must contain @ and . (dot) domain',
  password: 'Password must contain alphabet, number, and symbol (ex: mypassword!@44)',
  minValue: '{attribute} minimum is {min}',
  maxValue: '{attribute} maximum is {max}',
  minLength: '{attribute} minimum length is {min}',
  maxLength: '{attribute} maximum length is {max}',
  url: '{attribute} field contains an invalid url',
  numeric: '{attribute} field is must be numeric',
  alpha: '{attribute} field is must be alphabet',
  alphaSpace: '{attribute} field is must be alphabet',
  date: '{attribute} field date is invalid range',
  alphaNum: '{attribute} field only allow alphabet and number',
  username: '{attribute} field only allow alphabet, number, - , _ , @, and . (dot).',
  phoneNumber: 'Invalid phone number format',
  sameAsPassword: 'Re-enter New Password does not match New Password',
  sameAsCreatedPassword: 'Your confirmation password does not match the password you entered.',
  isNotSameAsNewPassword: 'New Password can not be same with Current Password',
  sameAs: 'The {attribute} entered does not match',
  invalidOpenHour: 'must be less than close hour',
  invalidCloseHour: 'must be more than open hour',
  phone: '{attribute} field contains an invalid phone format',
  invalidDateStart: 'Start date must be more than End date',
  invalidDateEnd: 'End date must be less than Start date',
  available: '{attribute} already exists',
  moreThanMin: '{attribute} must be more than {min}',
  lessThanMax: '{attribute} must be less than {max}',
};
