/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBaseFormGroup: typeof import('@components/base/AppBaseFormGroup.vue')['default']
    AppBaseSvg: typeof import('@components/base/AppBaseSvg.vue')['default']
    AppBaseToast: typeof import('@components/base/AppBaseToast.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
